#ifndef MSRP_DNSRESULTHANDLER_HXX
#define MSRP_DNSRESULTHANDLER_HXX

#include <asio.hpp>

#include "DnsResultSinkImpl.hxx"

namespace msrp
{

template<
   typename Query,
   typename Handler,
   typename PostFunction
   >
class DnsResultHandler : public DnsResultSinkImpl
{
   public:
      DnsResultHandler(asio::io_service& fifo, const Handler& handler, const PostFunction& post) :
         mFifo(fifo), mHandler(handler), mPost(post)
      {}

      virtual ~DnsResultHandler()
      {}

   private:
      virtual void onDnsResult(const resip::DNSResult<typename Query::Type>& result)
      {
         mFifo.post(boost::bind(mHandler, result));

         mPost(this);
      }

      asio::io_service& mFifo;

      // !cb! std::unary_function<resip::DNSResult<Query::Type>, void>
      //
      // It is important that your address vector parameter is not a ref&,
      // and forces a copy, since this handler will be deleted by the time
      // mHandler is called by the asio::io_service dispatcher.
      const Handler mHandler;

      // !cb! std::unary_function<resip::DnsResultSink*, void> (cleanup)
      const PostFunction mPost;
};

}

#endif

// Copyright 2007 Chris Bond
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
