#ifndef MSRP_MESSAGESESSIONBASE_HXX
#define MSRP_MESSAGESESSIONBASE_HXX

#include <cstddef>

#include <boost/signals.hpp>
#include <boost/shared_ptr.hpp>

#include "msrp/Message.hxx"
#include "msrp/Mutex.hxx"

namespace msrp
{

class MessageSessionBase
{
   public:
      MessageSessionBase(const Message& m);

      virtual ~MessageSessionBase();

      virtual void cancel() = 0;

      std::size_t size() const;
      std::size_t transferred() const;

      bool complete() const;
      bool interrupted() const;

      const Message& message() const;
      Message& message();

      const std::string messageId() const;

      boost::signal0<void>& onComplete();

      const boost::posix_time::ptime& lastTransfer() const;

   protected:
      mutable Mutex mMutex;

      Message mMessage;

      std::size_t mSize;
      std::size_t mTransferred;

      bool mComplete;
      bool mInterrupted;

      boost::posix_time::ptime mLastTransfer;

      boost::signal0<void> mCompleteEvent;
};

}

#endif

// Copyright 2007 Chris Bond
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
