#include <boost/spirit.hpp>

#include "msrp/System.hxx"
#include "msrp/AuthParser.hxx"
#include "msrp/ByteRange.hxx"
#include "msrp/LiteralBoolean.hxx"
#include "msrp/ParserFactory.hxx"
#include "msrp/ParseUri.hxx"
#include "msrp/ParseMessage.hxx"
#include "msrp/Report.hxx"
#include "msrp/Status.hxx"

using namespace msrp;
using namespace boost;

template<typename ParserT>
scoped_ptr<ParserT> ParserFactory<ParserT>::Instance;

template scoped_ptr<spirit::uint_parser<> > ParserFactory<spirit::uint_parser<> >::Instance;

template scoped_ptr<spirit::uint_parser<unsigned, 16> >
   ParserFactory<spirit::uint_parser<unsigned, 16> >::Instance;

template scoped_ptr<spirit::uint_parser<unsigned, 16, 8, 8> >
   ParserFactory<spirit::uint_parser<unsigned, 16, 8, 8> >::Instance;

#ifdef ENABLE_AUTHTUPLE
template scoped_ptr<parser::Auth<true> >
   ParserFactory<parser::Auth<true> >::Instance;
template scoped_ptr<parser::Auth<false> >
   ParserFactory<parser::Auth<false> >::Instance;
template scoped_ptr<QopParser> ParserFactory<QopParser>::Instance;
#endif

template scoped_ptr<parser::LiteralBoolean> ParserFactory<parser::LiteralBoolean>::Instance;
template scoped_ptr<parser::ByteRange> ParserFactory<parser::ByteRange>::Instance;
template scoped_ptr<parser::FailureReport> ParserFactory<parser::FailureReport>::Instance;
template scoped_ptr<parser::Message> ParserFactory<parser::Message>::Instance;
template scoped_ptr<parser::MessageId> ParserFactory<parser::MessageId>::Instance;
template scoped_ptr<parser::Mime> ParserFactory<parser::Mime>::Instance;
template scoped_ptr<parser::Path> ParserFactory<parser::Path>::Instance;
template scoped_ptr<parser::Status> ParserFactory<parser::Status>::Instance;
template scoped_ptr<parser::SuccessReport> ParserFactory<parser::SuccessReport>::Instance;
template scoped_ptr<parser::Uri> ParserFactory<parser::Uri>::Instance;

// Copyright 2007 Chris Bond
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
