#ifndef MSRP_REPORT_HXX
#define MSRP_REPORT_HXX

#include <boost/spirit.hpp>
#include <boost/spirit/actor.hpp>
#include <boost/spirit/attribute/closure.hpp>

namespace msrp
{

namespace parser
{

struct SuccessReportClosure :
   boost::spirit::closure<SuccessReportClosure, bool>
{
   member1 success;
};

struct SuccessReport :
   boost::spirit::grammar<SuccessReport, SuccessReportClosure::context_t>
{
   template<typename ScannerT>
   struct definition
   {
      definition(const SuccessReport& self)
      {
         root
            = boost::spirit::str_p("yes")[self.success = phoenix::val(true)]
            | boost::spirit::str_p("no") [self.success = phoenix::val(false)]
            ;
      }

      boost::spirit::rule<ScannerT> root;
      boost::spirit::rule<ScannerT> const& start() const
      {
         return root;
      }
   };
};

struct FailureReportClosure : boost::spirit::closure<FailureReportClosure, int>
{
   member1 failure;
};

struct FailureReport :
   boost::spirit::grammar<FailureReport, FailureReportClosure::context_t>
{
   template<typename ScannerT>
   struct definition
   {
      definition(const FailureReport& self)
      {
         root                                // FailureReport::Report enum
            = boost::spirit::str_p("no")     [self.failure = phoenix::val(0)]
            | boost::spirit::str_p("yes")    [self.failure = phoenix::val(1)]
            | boost::spirit::str_p("partial")[self.failure = phoenix::val(2)]
            ;
      }

      boost::spirit::rule<ScannerT> root;
      boost::spirit::rule<ScannerT> const& start() const
      {
         return root;
      }
   };
};

} // namespace parser

}

#endif

// Copyright 2007 Chris Bond
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
