#ifndef MSRP_SESSIONFACTORY_HXX
#define MSRP_SESSIONFACTORY_HXX

#include <map>
#include <memory>
#include <vector>

#include <asio.hpp>

#include <boost/noncopyable.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/weak_ptr.hpp>

#include <rutil/dns/QueryTypes.hxx>

#include "msrp/ConnectionPool.hxx"
#include "msrp/DnsService.hxx"
#include "msrp/Mutex.hxx"
#include "msrp/Uri.hxx"

namespace msrp
{

class Session;

class SessionFactory :
   private boost::noncopyable
{
   public:
      // !cb! callback for post-DNS session creation
      typedef boost::function2<void, boost::shared_ptr<Session>, const asio::error&> Callback;

      SessionFactory(asio::io_service&);

      ~SessionFactory();

      asio::io_service& service();

      boost::shared_ptr<Session> answer(const Uri& peer, const Uri& self, Callback handler);

      boost::shared_ptr<Session> offer(const asio::ip::tcp::endpoint& bind, const Uri& self);

      void shutdown();

   private:
      struct RequestInfo
      {
         Uri self;
         Uri peer;
         Callback handler;
      };

      void onSrvResult(const RequestInfo, const resip::DNSResult<resip::DnsSrvRecord>&);

      void onDnsResult(const RequestInfo, const std::vector<asio::ip::address>&);

      boost::shared_ptr<Session> answer(const asio::ip::tcp::endpoint& peer, const Uri& self);
      
      mutable Mutex mMutex;

      asio::io_service& mService;

      boost::shared_ptr<ConnectionPool> mPool;

      DnsService mDns;
};

}

#endif

// Copyright 2007 Chris Bond
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
